name: Deploy Arch Repo

on:
  push:
    branches:
      - main
    paths:
      - 'packages/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install pacman tools
        run: sudo apt-get update && sudo apt-get install -y pacman

      - name: Build repo database
        run: |
          mkdir -p packages
          repo-add packages/arcat-repo.db.tar.gz packages/*.pkg.tar.zst

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./packages
