name: Deploy Arch Repo

on:
  push:
    branches:
      - main
    paths:
      - 'packages/**'

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    container: archlinux:latest

    steps:
      - uses: actions/checkout@v3

      - name: Update system and install tools
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm pacman git

      - name: Build repo database
        run: |
          mkdir -p packages
          repo-add packages/arcat-repo.db.tar.gz packages/*.pkg.tar.zst

      - name: Upload artifact for Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./packages

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
